version: '3'
services:
  backend-service:
    image: backend_image
    depends_on:
      - postgres
    deploy:
      replicas: 1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5433/lic
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - front
      - back
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-service.rule=Host(`backend-service.localhost`)"
      - "traefik.http.services.backend-service.loadbalancer.server.port=8080"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lic
    ports:
      - "5434:5433"
    networks:
      - back

  reverse-proxy:
    image: traefik:v3.2
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker
      - --accesslog=true
      - --accesslog.filepath=/var/log/traefik/access.log
      - --log.level=DEBUG
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8084:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_logs:/var/log/traefik
    networks:
      - front
      - back

networks:
  back:
    driver: bridge
    external: true
  front:
    driver: bridge
    external: true

volumes:
  traefik_logs:
